# Generated by Django 5.2.7 on 2025-10-30 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code_iso', models.CharField(default='N/A', max_length=5)),
                ('capitale', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('categorie', models.CharField(blank=True, max_length=100, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('coordonnees_gps', models.CharField(blank=True, max_length=100, null=True)),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('note', models.FloatField(default=0.0)),
                ('reviews', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('tripadvisor_url', models.URLField(blank=True, null=True)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.pays')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Compilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('attractions', models.ManyToManyField(to='explorer.attraction')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.profil')),
            ],
        ),
    ]
