# Generated by Django 5.2.7 on 2025-10-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attraction',
            options={'ordering': ['-note', '-likes'], 'verbose_name': 'Attraction', 'verbose_name_plural': 'Attractions'},
        ),
        migrations.RenameField(
            model_name='attraction',
            old_name='reviews',
            new_name='nb_photos',
        ),
        migrations.AddField(
            model_name='attraction',
            name='awards',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='coordonnees_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='horaires',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='nb_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attraction',
            name='type',
            field=models.CharField(choices=[('attraction', 'Attraction'), ('restaurant', 'Restaurant'), ('hotel', 'Hôtel'), ('autre', 'Autre')], default='attraction', max_length=30),
        ),
    ]
